default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: Master@123
  host: localhost
  port: 3306

development:
  <<: *default
  database: backbencher_pos_development

test:
  <<: *default
  database: backbencher_pos_test

production:
  <<: *default
  database: backbencher_pos_production
