default: &default
  adapter: mysql2
  encoding: utf8
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
  port: 3306

development:
  <<: *default
  database: backbencher_pos_development

test:
  <<: *default
  database: backbencher_pos_test

production:
  <<: *default
  database: backbencher_pos_production
